on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir foo && touch foo/bar.txt
      - uses: actions/upload-artifact@v2
        with:
          path: foo/bar.txt
          name: bar
